import Layout from '../Layout'
import Heading from '../components/Heading'

function Home() {
  return (
    <Layout>
      <Heading title="Was ist Bloodbowl?" />
        <div className="text-sm sm:flex gap-x-6 text-justify">
          <div>
            <p>Blood Bowl ist ein Brettspiel, bei dem sich zwei Spieler, hier Coaches genannt, mit aus Fantasy-Figuren zusammen gesetzten Mannschaften in einem fiktiven Sport messen, der an American Football erinnert. Das Spielfeld ist 26 quadratische Felder lang und 15 breit und in zwei gleich große Hälften geteilt, die jeweils einer Mannschaft zugewiesen sind. Die hinterste Felderreihe in jeder Hälfte ist die Endzone der jeweiligen Mannschaft. Zu Beginn eines Spielabschnittes (Drive) wird der Ball per Kickoff in die Hälfte des Gegners geschossen. Die Mannschaften sind nun abwechselnd am Zug. Von jeder Mannschaft stehen zu Beginn eines Drives maximal 11 Spieler auf dem Platz. Es gilt, den Ball zu sichern und durch Laufen oder Werfen bis in die Endzone des Gegners zu befördern und so Touchdowns zu erzielen, während der Gegner versucht, dies zu verhindern. Nach einem Touchdown führt die Mannschaft einen Kickoff aus, die den Touchdown erzielt hat. Drives enden außerdem, wenn beide Spieler jeweils die achte oder sechzehnte Spielrunde beendet haben. Es gewinnt die Mannschaft, der es gelingt, in 16 Runden mehr Touchdowns zu erzielen als der Gegner. </p>
            <p>Den Spielern stehen jeweils verschiedene Spielmechanismen zur Verfügung, um ihre Ziele zu erreichen. Jeder Spieler einer Mannschaft darf in einer Runde eine von sechs möglichen Aktionen ausführen: Bewegen, Blocken (einen Gegner angreifen, der in einem benachbarten Feld steht), Passen, Ballübergabe, Foulen oder Blitzen (eine Kombination aus Bewegen und Blocken), wobei die vier zuletzt genannten jeweils pro Runde nur von einem Spieler einer Mannschaft ausgeführt werden dürfen und streng darauf zu achten ist, dass die Aktionen der einzelnen Spieler nacheinander durchgeführt werden. Dabei kommen, je nach Aktion, verschiedene Würfelmechanismen zum Einsatz. Misslingt jedoch eine Ballaktion (Ballaufheben, Werfen, Fangen oder Übergeben) oder fällt ein eigener Spieler beim Blocken oder Ausweichen hin, bedeutet das das sofortige Ende des Zuges: Turnover. </p>
            <p>Die ballführende Mannschaft wird also versuchen den Ball zu sichern und einen Touchdown zu erzielen, während der Gegner versucht, das zu verhindern, vielleicht sogar den Ball zu erobern und selbst zu punkten. Üblicherweise behält dabei derjenige Coach die Überhand, dem es besser gelingt, die spezifischen Stärken seines Teams zur Geltung zu bringen während er seine Schwächen vermeidet. </p>
          </div>
          <div>
            <p>Die zur Verfügung stehenden Spielertypen unterscheiden sich nämlich stark voneinander: erstens durch die Basischarakteristika Bewegungsweite, Stärke, Geschicklichkeit und Rüstungswert, zweitens durch besondere Fertigkeiten. Ein Coach muss also seine Strategie danach ausrichten, ob ihm vor allem schnelle, leicht gerüstete und geschickte Spieler zur Verfügung stehen oder schwer gepanzerte, schwerfällige Raufbolde. Dies bestimmt sich wiederum vor allem danach, welche von insgesamt 24 zur Verfügung stehenden Rassen ein Coach sich ausgesucht hat. Elegante Elfen, grobschlächtige Orks, verschlagene Skaven, gewaltige Oger (die mit einer Rasselbande von ballgroßen Snotlings auflaufen), nichtswürdige Goblins, bärtige Zwerge, blutlüsterne Chaosmutanten oder, oder, oder. Eine gute Strategie bezieht außerdem mit ein, was für Spielern man gegenüber steht. Mag eine brüderliche Schlägerei unter Elfen noch angehen, wäre jeder der Elfencoaches gut beraten, sich einem Zwergenteam gegenüber in sicherem Abstand zum Gegner zu bewegen und allenfalls mit einzelnen überfallartigen Angriffen Nadelstiche zu setzen und vielleicht Wirkung zu erzielen. </p>
            <p>Blood Bowl ist ein brutales Spiel. Die Spieler (nicht die Coaches!) riskieren bei jeden Spiel ihre Gesundheit und mehr. Nicht nur klauenbewehrte Chaoskrieger und Kettensägen schwingende Goblins können auf dem Platz auf einen warten, auch der alltägliche Block gegen einen menschlichen Werfer, ein Routineausweichmanöver oder eine Unachtsamkeit beim Sprinten können schwere Verletzungen zur Folge haben oder sogar mit dem Tod eines Spielers enden. Bereit stehende Apotheker sind ihr Geld nicht immer wert. Spieler, die überleben, sammeln hingegen Erfahrungspunkte, können so Fertigkeiten oder sogar Verbesserungen ihrer Charakteristika erhalten und werden so nach und nach zu Stars. </p>
            <p>Blood Bowl lässt sich zwar auch als Einzelmatch spielen, die größte Faszination entwickelt es aber in Turnier- oder Ligaformaten. Beides ist sowohl in Form des klassischen Brettspiels (Tabletop) als auch online über das Internet möglich. Tabletop-Spiele finden in der Regel im Rahmen lokal organisierter Ligen oder von Turnieren statt, welche an einem oder zwei Tagen mit 3, 4 oder 6 Partien im Schweizer System ausgetragen werden und durchaus auch ein überregionales, bisweilen sogar internationales Publikum ansprechen.</p>
          </div>
        </div>
    </Layout>
  )
}

export default Home
